### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tomlenth**
Added 7 samples from oneAPI samples repo.  These all fall under the Math and Science category.

### CODE REVIEW

**Comment by FCLC** [comment]
Hey @tomlenth! LGTM, just have to resolve the conflicts

**Comment by tomlenth** [comment]
@sramkrishna  did you want to merge this directly or I thought maybe you were going to insert the Intel samples into specific categories.  I think my merge is a little stale.  Regardless, really think these samples would be helpful to the community.

**Comment by sramkrishna** [comment]
I can take care of it and create a new PR

**Comment by sramkrishna** [comment]
I have added the 7 projects in this PR into the main repo. Thank you for the contribution, Tom!

**Pull request closed without merging**
